2016-11-18 14:01:30,663 - 46 - INFO - log file:/data/BI/vdw/log/buff/buff.dw_user/20161118/target_table_load_handler.py_20161118140130.log
2016-11-18 14:01:30,663 - 47 - INFO - /data/BI/vdw/bat/target_table_load_handler.py buff.dw_user buff.dw_user.ins.sql
2016-11-18 14:01:30,664 - 48 - INFO - sql_file:/data/BI/vdw/sql/buff/buff.dw_user.ins.sql
2016-11-18 14:01:30,664 - 49 - INFO - tmp_sql_file:/data/BI/vdw/tmp/buff/buff.dw_user.ins.sql20161118140130
2016-11-18 14:01:30,664 - 50 - INFO - UOW:20161115000000,20161116000000
2016-11-18 14:01:30,664 - 61 - INFO - command: psql -h 172.16.15.131 -p 5432 -d bidw -v ON_ERROR_STOP=1 -U vu_buff -f /data/BI/vdw/tmp/buff/buff.dw_user.ins.sql20161118140130
2016-11-18 14:01:30,664 - 62 - INFO - {'{UOW_FROM}': '20161115000000', '{UOW_TO}': '20161116000000', '{ETL_ID}': 'buff.dw_user', '{TABLE_ID}': 'dw_user', '{LEVEL_ID}': 'buff'}
2016-11-18 14:01:30,670 - 71 - INFO - DELETE 0
2016-11-18 14:01:30,670 - 71 - INFO - psql:/data/BI/vdw/tmp/buff/buff.dw_user.ins.sql20161118140130:70: ERROR:  column "src_create_date" of relation "buff_user" does not exist
2016-11-18 14:01:30,671 - 71 - INFO - LINE 28: src_create_date ,
2016-11-18 14:01:30,671 - 71 - INFO - ^
2016-11-18 14:01:30,671 - 75 - ERROR - sql executed false.
